# Generated by Django 4.0.1 on 2022-04-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_url', models.CharField(blank=True, default='', max_length=500)),
                ('rank', models.CharField(blank=True, default='', max_length=500)),
                ('exchange', models.CharField(blank=True, default='', max_length=500)),
                ('trust_score', models.CharField(blank=True, default='', max_length=500)),
                ('total_24h_volume_normalized', models.CharField(blank=True, default='', max_length=500)),
                ('total_24h_volume', models.CharField(blank=True, default='', max_length=500)),
                ('visits_similarWeb', models.CharField(blank=True, default='', max_length=500)),
                ('coins', models.CharField(blank=True, default='', max_length=500)),
                ('pairs', models.CharField(blank=True, default='', max_length=500)),
                ('time_stamp', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='NftTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_url', models.CharField(blank=True, default='', max_length=500)),
                ('rank', models.CharField(blank=True, default='', max_length=500)),
                ('nft', models.CharField(blank=True, default='', max_length=500)),
                ('floor_price', models.CharField(blank=True, default='', max_length=500)),
                ('total_24h', models.CharField(blank=True, default='', max_length=500)),
                ('market_cap', models.CharField(blank=True, default='', max_length=500)),
                ('total_24h_volume', models.CharField(blank=True, default='', max_length=500)),
                ('owners', models.CharField(blank=True, default='', max_length=500)),
                ('total_24h_owners', models.CharField(blank=True, default='', max_length=500)),
                ('total_assets', models.CharField(blank=True, default='', max_length=500)),
                ('time_stamp', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
    ]
