# Generated by Django 4.0.1 on 2022-04-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailedExchangeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(blank=True, default='', max_length=500)),
                ('rank', models.CharField(blank=True, default='', max_length=500)),
                ('coins', models.CharField(blank=True, default='', max_length=500)),
                ('pairs', models.CharField(blank=True, default='', max_length=500)),
                ('price', models.CharField(blank=True, default='', max_length=500)),
                ('spread', models.CharField(blank=True, default='', max_length=500)),
                ('Depth_positive_2', models.CharField(blank=True, default='', max_length=500)),
                ('Depth_negative_2', models.CharField(blank=True, default='', max_length=500)),
                ('total_24h_volume', models.CharField(blank=True, default='', max_length=500)),
                ('volume_percentage', models.CharField(blank=True, default='', max_length=500)),
                ('last_traded', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DetailedNftTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nft', models.CharField(blank=True, default='', max_length=500)),
                ('floor_price', models.CharField(blank=True, default='', max_length=500)),
                ('market_cap', models.CharField(blank=True, default='', max_length=500)),
                ('total_24h_volume', models.CharField(blank=True, default='', max_length=500)),
                ('floor_price_usd', models.CharField(blank=True, default='', max_length=500)),
                ('floor_price_percentage', models.CharField(blank=True, default='', max_length=500)),
                ('market_cap_usd', models.CharField(blank=True, default='', max_length=500)),
                ('market_cap_percentage', models.CharField(blank=True, default='', max_length=500)),
                ('top_nfts_by_market_cap', models.CharField(blank=True, default='', max_length=500)),
                ('stat_table_container', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
    ]
