# Generated by Django 4.0.1 on 2022-04-01 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_detailedexchangetable_detailednfttable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailedexchangetable',
            old_name='Depth_negative_2',
            new_name='depth_negative_2',
        ),
        migrations.RenameField(
            model_name='detailedexchangetable',
            old_name='Depth_positive_2',
            new_name='depth_positive_2',
        ),
    ]
