# Generated by Django 4.0.1 on 2022-04-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_rename_depth_negative_2_detailedexchangetable_depth_negative_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailednfttable',
            name='stat_table_container',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='detailednfttable',
            name='top_nfts_by_market_cap',
            field=models.TextField(blank=True, default=''),
        ),
    ]
