# Generated by Django 4.0.1 on 2022-04-05 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_detailedexchangetable_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailedexchangetable',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='root.exchangetable'),
        ),
        migrations.AddField(
            model_name='detailednfttable',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='root.nfttable'),
        ),
    ]
