# Generated by Django 4.0.1 on 2022-04-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_detailedexchangetable_parent_detailednfttable_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailedexchangetable',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='detailednfttable',
            name='parent',
        ),
        migrations.AddField(
            model_name='detailedexchangetable',
            name='parent_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='detailednfttable',
            name='parent_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
